from OpenMpipi import *

dhh1_sequence = 'MADALASQLNNTSLGDANSDAKWKDQLKTPAKDARPQTEDVTATKGLEFEDFYIKRELMMGIFEAGFEKPSP\
IQEETIPVALTGRDILARAKNGTGKTAAFVIPTLERINPKSTKTQALILVPTRELALQTSHVCKTLGKHLGINVMVTTGGTGLMDDIIRLNDAVHILVGTPGRVLDLASKGVADLSE\
CPTFVMDEADKLLSPEFTPVIEQLLSFHPKDRQVMLFSATFPLIVKSFKDKHMRNPYEINLMDELTLRGITQYYAFVEEKQKVHCLNTLFSKLQINQSIIFCNSTNRVELLAKKITELGYSCFYSHARMLQQHRNRVFHDFRNGVCRNLVCSDLLTRGIDIQAVNVVINFDFPKNAETYLHRIGRSGRFGHLGLAINLINWDDRFNLYKIE\
QELGTEIQPIPQNIDKKLYVYDSPDTIPRPISNPSQPPQATGMPSGQHIGDRRHNNHPNGGHYQYNRGRGSYRGGRGQGPRRNVQHDQNRYNASQGQHQSGKSQAAPVS'

dhh1_chain = MDP("Dhh1", dhh1_sequence, [[i for i in range(18,248)], [i for i in range(258, 426)]], './dhh1_atomistic.pdb')

chains = {
    dhh1_chain:200
}

build_and_equilibrate_model(chains, equi_time=500*unit.nanosecond, pulling_time=20*unit.nanosecond)
